POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRpaW5hMyIsImlkIjoiNjFlN2QyYTRhYmFmNDJlOWQ5OWFjYTM2IiwiaWF0IjoxNjQyNTgyNzAyfQ.0o1h6ZpY5o3M9AsuT9ljkF6Skn915-lpdO12z8kYXdE

{
  "title": "Should have different user",
  "author": "Tiina3",
  "url": "www.tiina.com"
}
