POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Another really fun blog",
  "author": "Tiina Teekkari",
  "userId": "61c08bcbf79dabb1749d848e",
  "url": "www.tiina.com",
  "likes": 4
}
