POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRpaW5hIiwiaWQiOiI2MWMxYzRkM2IyNGJkMWI1YWY2ZTYxN2MiLCJpYXQiOjE2NDAwODk0Mjd9.cKfXEvKvktkzw8nslbEGA3eajG8ysUfnSt0iAqICC8E

{
  "title": "Another really fun blog",
  "author": "Tiina Teekkari",
  "url": "www.tiina.com",
  "likes": 4
}
